In [20]:
import pandas as pd
df = pd.read_csv("../data/train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [21]:
df.shape

(891, 12)

In [22]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [23]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [25]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [26]:
#drop unnecessary columns
df = df.drop(columns=['Cabin','PassengerId','Name','Ticket'])

In [27]:
#filling missing values
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

#check
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [28]:
#Encoding categorical data
df['Sex'] = df['Sex'].map({'male':1,'female':2})
df['Embarked'] = df['Embarked'].map({'S':1,'C':2,'Q':3})
df.head(20)

    Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          0       3    1  22.0      1      0   7.2500         1
1          1       1    2  38.0      1      0  71.2833         2
2          1       3    2  26.0      0      0   7.9250         1
3          1       1    2  35.0      1      0  53.1000         1
4          0       3    1  35.0      0      0   8.0500         1
5          0       3    1  28.0      0      0   8.4583         3
6          0       1    1  54.0      0      0  51.8625         1
7          0       3    1   2.0      3      1  21.0750         1
8          1       3    2  27.0      0      2  11.1333         1
9          1       2    2  14.0      1      0  30.0708         2
10         1       3    2   4.0      1      1  16.7000         1
11         1       1    2  58.0      0      0  26.5500         1
12         0       3    1  20.0      0      0   8.0500         1
13         0       3    1  39.0      1      5  31.2750         1
14         0       3    2  14.0      0      0   7.8542         1
15         1       2    2  55.0      0      0  16.0000         1
16         0       3    1   2.0      4      1  29.1250         3
17         1       2    1  28.0      0      0  13.0000         1
18         0       3    2  31.0      1      0  18.0000         1
19         1       3    2  28.0      0      0   7.2250         2

In [32]:
#Split dataframe
from sklearn.model_selection import train_test_split
x = df.drop('Survived',axis =1)
y = df['Survived']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)

(712, 7)
(179, 7)

In [1]:
#Model training
from sklearn.linear_model import LogisticRegression
model =LogisticRegression(max_iter=1000)
predictions = model.fit(x_train,y_train)

NameError: name 'x_train' is not defined