In [34]:
import pandas as pd
df = pd.read_csv("../data/train.csv")
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [35]:
df.shape

(891, 12)

In [36]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [37]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [39]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [40]:
#drop unnecessary columns
df = df.drop(columns=['Cabin','PassengerId','Name','Ticket'])

In [41]:
#filling missing values
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

#check
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [42]:
#Encoding categorical data
df['Sex'] = df['Sex'].map({'male':1,'female':2})
df['Embarked'] = df['Embarked'].map({'S':1,'C':2,'Q':3})
df.head(20)

    Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          0       3    1  22.0      1      0   7.2500         1
1          1       1    2  38.0      1      0  71.2833         2
2          1       3    2  26.0      0      0   7.9250         1
3          1       1    2  35.0      1      0  53.1000         1
4          0       3    1  35.0      0      0   8.0500         1
5          0       3    1  28.0      0      0   8.4583         3
6          0       1    1  54.0      0      0  51.8625         1
7          0       3    1   2.0      3      1  21.0750         1
8          1       3    2  27.0      0      2  11.1333         1
9          1       2    2  14.0      1      0  30.0708         2
10         1       3    2   4.0      1      1  16.7000         1
11         1       1    2  58.0      0      0  26.5500         1
12         0       3    1  20.0      0      0   8.0500         1
13         0       3    1  39.0      1      5  31.2750         1
14         0       3    2  14.0      0      0   7.8542         1
15         1       2    2  55.0      0      0  16.0000         1
16         0       3    1   2.0      4      1  29.1250         3
17         1       2    1  28.0      0      0  13.0000         1
18         0       3    2  31.0      1      0  18.0000         1
19         1       3    2  28.0      0      0   7.2250         2

In [43]:
#Split dataframe
from sklearn.model_selection import train_test_split
x = df.drop('Survived',axis =1)
y = df['Survived']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)

(712, 7)
(179, 7)

In [44]:
#Model training and prediction
from sklearn.linear_model import LogisticRegression
model =LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
predictions = model.predict(x_test)
predictions[:10]

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1])

In [45]:
#Model Evaluation
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,predictions)
print(accuracy)

0.7988826815642458

In [46]:
#Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,predictions)
print(cm)

[[89 16]
 [20 54]]

In [47]:
#Classification report
from sklearn.metrics import classification_report
c_report = classification_report(y_test,predictions)
print(c_report)

              precision    recall  f1-score   support

           0       0.82      0.85      0.83       105
           1       0.77      0.73      0.75        74

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

In [48]:
#Co-effiient interpretation
feature_names = x.columns
for feature,weight in zip(feature_names,model.coef_[0]):
    print (f" {feature} : {weight}" )

 Pclass : -0.9581160646626204
 Sex : 2.581449594765328
 Age : -0.03116448142825963
 SibSp : -0.3028679456452497
 Parch : -0.10057460586528083
 Fare : 0.0028618252796473666
 Embarked : 0.22256321739497686

In [49]:
#Feaure Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
print(x_train_scaled[:5])

[[-1.61413602 -0.7243102   1.25364106 -0.47072241 -0.47934164 -0.07868358
  -0.54803535]
 [-0.40055118 -0.7243102  -0.47728355 -0.47072241 -0.47934164 -0.37714494
  -0.54803535]
 [ 0.81303367 -0.7243102   0.21508629 -0.47072241 -0.47934164 -0.47486697
  -0.54803535]
 [ 0.81303367 -0.7243102  -0.24649361  0.37992316 -0.47934164 -0.47623026
  -0.54803535]
 [ 0.81303367  1.38062393 -1.78509326  2.93185988  2.04874166 -0.02524937
  -0.54803535]]

In [50]:
#Model train with scaled data & comapring accuracy
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

scaled_model = LogisticRegression(max_iter=1000)
scaled_model.fit(x_train_scaled,y_train)
scaled_predictions = scaled_model.predict(x_test_scaled)
scaled_accuracy = accuracy_score(scaled_predictions,y_test)
print(scaled_accuracy)

0.7988826815642458

In [51]:
feature_names = x.columns

for feature, weight in zip(
    feature_names,
    scaled_model.coef_[0]
):
    print(feature, ":", weight)

Pclass : -0.8042721201193487
Sex : 1.2709164332434582
Age : -0.4048338418892639
SibSp : -0.35983877635996336
Parch : -0.08929843202569744
Fare : 0.14366551353839072
Embarked : 0.14033908036381285

In [ ]:
#Decision tree and overfitting analysis
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

tree_model = DecisionTreeClassifier(random_state=42)
tree_model.fit(x_train,y_train)
tree_predictions = model.predict(x_test)

tree_accuracy = accuracy_score(tree_predictions,y_test)
print(tree_accuracy)

print(tree_model.score(x_train,y_train))

0.7988826815642458
0.9789325842696629

In [54]:
#Handling Overfitting
limited_tree = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)

limited_tree.fit(x_train, y_train)

print(limited_tree.score(x_train,y_train))
print(limited_tree.score(x_test,y_test))

0.8342696629213483
0.7988826815642458

In [ ]:
#Cross Validation
from sklearn.model_selection import cross_val_score

cv_score = cross_val_score(
    model,
    x,
    y,
    cv=5
)
print(cv_score)